#!/bin/bash
#
# opt file to compile mitgcm on iris
# architecture: Linux iris.ssec.wisc.edu 2.6.32-431.11.2.el6.x86_64 #1 SMP Tue Mar 25 19:59:55 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
# 
RSHCOMMAND="ssh -x"
FC=$I_MPI_ROOT/intel64/bin/mpif90
CC=$I_MPI_ROOT/intel64/bin/mpicc 
LINK=$I_MPI_ROOT/intel64/bin/mpif90
DEFINES='-DWORDLENGTH=4 -DALLOW_USE_MPI -DALWAYS_USE_MPI'
CPP='cpp  -traditional -P'
NOOPTFLAGS='-O0'
MAKEDEPEND='/scratch/luke/compile_michigan/code/tool/makedepend'
INCLUDES="-I$I_MPI_ROOT/intel64/include -I$SSEC_NETCDF_INC -I/scratch/luke/compile_michigan/code/source/model/inc"
LIBS="-L$SSEC_NETCDF_LIB -lnetcdf" 

FFLAGS='-fc=ifort  -132 -r8 -i4 -fp-model  -convert big_endian -assume byterecl'
FFLAGS='-fc=ifort -DWORDLENGTH=4 -DALLOW_USE_MPI -DALWAYS_USE_MPI -O2 -132 -r8 -i4 -fp-model precise -convert big_endian -assume byterecl'
FOPT='-O2 '

